{ pkgs, config, ... }: {

  users = {
    defaultUserShell = pkgs.bash;
    users = {
      deploy = {
        isNormalUser = true;
        extraGroups = [ "wheel" ];
        home = "/home/deploy";
        shell = pkgs.bash;
        # generated by `mkpasswd -m scrypt`

        # /etc/ssh/authorized_keys.d/${user}
        openssh.authorizedKeys.keyFiles =
          "sh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOoRjB5AqGrenuJz8jcW9qeIHgV2uJ8TySp/vpzyLab5 nguyendinhnhattai.work@gmail.com";
      };
      root = {
        inherit (config.users.users."deploy") initialHashedPassword;
        openssh.authorizedKeys.keyFiles =
          "sh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOoRjB5AqGrenuJz8jcW9qeIHgV2uJ8TySp/vpzyLab5 nguyendinhnhattai.work@gmail.com";
      };
    };
  };
}
